import { StyleSheet } from "react-native";

export default styles = StyleSheet.create({
    container: {
        width: '100%',
        alignItems: 'center',
        backgroundColor: '#DFEDEB',
        flex: 1,
    },
    scrollview: {
        backgroundColor: '#DFEDEB',
        width: '100%',
        alignItems: 'center',
        flex: 1,
    },
    button: {
        backgroundColor: "#B30000",
        // vermelho escuro #B30000
        width: "90%",
        borderRadius: 5,
        padding: "4%",
        alignItems: "center",
        marginTop: "5%",
        borderColor: "#B1B1B1",
        borderWidth: 1,
        boxShadowColor: "#000",
        boxShadowOffset: {
            width: 0,
            height: 2,
        },
        boxShadowOpacity: .25,
        boxShadowRadius: 3.84,
        elevation: 1,
    },
    buttonText: {
        color: "white",
        fontSize: 18,
    },
    containerField: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        backgroundColor: "#FEFEFE",
        padding: "2%",
        marginVertical: "2%",
        paddingHorizontal: "5%",
        boxShadowColor: "#000",
        boxShadowOffset: {
            width: 0,
            height: 2,
        },
        boxShadowOpacity: .25,
        boxShadowRadius: 3.84,
        elevation: 1,
    },
    titleField: {
        fontSize: 16,
        fontWeight: "bold",
        fontFamily: "sans-serif-light",
    },
    title: {
        fontSize: 24,
        fontWeight: "bold",
        fontFamily: "sans-serif-light",
        color: "#FEFEFE",
        marginBottom: "5%",
        marginTop: "10%",
    },
    headerModal: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        borderBottomWidth: 1,
        borderBottomColor: "#555",
        paddingHorizontal: 20,
        paddingVertical: 15,
    },
    modalTitle: {
        fontSize: 18,
        color: "#555",
    },
    modalCancel: {
        fontSize: 14,
        color: "#086972",
        fontWeight: "bold",
    },
    modalContent: {
        alignItems: "center",
        paddingVertical: "10%",
    },
    modalInput: {
        width: "80%",
        backgroundColor: "#fff",
        paddingHorizontal: "5%",
        paddingVertical: "2%",
        borderRadius: 10,
        fontSize: 16,
        borderWidth: 1,
        borderColor: "#086972",
        marginTop: "1%",
    },
    modalButton: {
        width: "80%",
        alignItems: "center",
        backgroundColor: "#086972",
        paddingVertical: "2%",
        borderRadius: 10,
        marginTop: "5%",
    },
})